name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: json, mbstring, intl
          tools: composer:v2, cs2pr

      - name: Install dependencies
        working-directory: bundle/WrapNotificatorBundle
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: PHP CS Fixer (dry-run)
        working-directory: bundle/WrapNotificatorBundle
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --ansi || true

      - name: PHPStan
        working-directory: bundle/WrapNotificatorBundle
        run: vendor/bin/phpstan analyse --no-progress --ansi

      - name: PHPUnit
        working-directory: bundle/WrapNotificatorBundle
        run: vendor/bin/phpunit --colors=always
