name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: json, mbstring, intl
          tools: composer:v2, cs2pr

      - name: Validate composer.json
        run: composer validate --no-check-publish --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Cache PHP CS Fixer cache
        uses: actions/cache@v4
        with:
          path: .php-cs-fixer.cache
          key: php-cs-fixer-${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('.php-cs-fixer.php') }}
          restore-keys: |
            php-cs-fixer-${{ runner.os }}-${{ matrix.php }}-

      - name: PHP CS Fixer (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --ansi

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress --ansi

#      - name: PHPUnit
#        env:
#          XDEBUG_MODE: coverage
#        run: vendor/bin/phpunit --colors=always
